### ISSUE TITLE
The file '/etc/openvpn/vars' was not found.

### ISSUE THREAD

**Issue by kiksia95** [Hexxonite/docker-openvpn-tap#1]
Hi, I'm trying to install it by your tips. and after _./install.sh_  i see sth like this

`Easy-RSA error:

The file '/etc/openvpn/vars' was not found.
Restarting docker_openvpn_tap ... done
Done setting up.
`

`Stopping docker_openvpn_tap ... done
Removing docker_openvpn_tap ... done
Building docker_openvpn_tap
Step 1/14 : FROM alpine:latest
 ---> a24bb4013296
Step 2/14 : RUN echo "http://dl-cdn.alpinelinux.org/alpine/edge/testing/" >> /etc/apk/repositories &&     apk add --update openvpn iptables bash easy-rsa bridge bridge-utils &&     ln -s /usr/share/easy-rsa/easyrsa /usr/local/bin &&     rm -rf /tmp/* /var/tmp/* /var/cache/apk/* /var/cache/distfiles/*
 ---> Using cache
 ---> 71c093a46041
Step 3/14 : ENV OPENVPN /etc/openvpn
 ---> Using cache
 ---> 35aa30a3b524
Step 4/14 : ENV EASYRSA /usr/share/easy-rsa
 ---> Using cache
 ---> 55d6c83f9511
Step 5/14 : ENV EASYRSA_PKI $OPENVPN/pki
 ---> Using cache
 ---> 26ed266e3954
Step 6/14 : ENV EASYRSA_VARS_FILE $OPENVPN/vars
 ---> Using cache
 ---> 2c2a4712b582
Step 7/14 : ENV EASYRSA_CRL_DAYS 3650
 ---> Using cache
 ---> b0b4c6efd0d8
Step 8/14 : VOLUME ["/etc/openvpn"]
 ---> Using cache
 ---> 238db3b9d1b7
Step 9/14 : EXPOSE 1194/udp
 ---> Using cache
 ---> 4c66c828ddcd
Step 10/14 : ADD bin /usr/local/bin/
 ---> Using cache
 ---> d9d5c5ffe4b6
Step 11/14 : RUN chmod a+x /usr/local/bin/*
 ---> Using cache
 ---> 2374f849bb7d
Step 12/14 : COPY up.sh /usr/share/up.sh
 ---> Using cache
 ---> 138cb9cd36a4
Step 13/14 : RUN chmod +x /usr/share/up.sh
 ---> Using cache
 ---> c9230ae05115
Step 14/14 : CMD ["ovpn_run_tap"]
 ---> Using cache
 ---> 14933af40129
Successfully built 14933af40129
Successfully tagged alpine/latest:latest
Creating docker_openvpn_tap ... done

Easy-RSA error:

The file '/etc/openvpn/vars' was not found.
Restarting docker_openvpn_tap ... done
Done setting up.
`

What I'm doing wrong? The Container cant start.

**Comment by Hexxonite** [comment]
Hi there, thanks for reporting this.
However, please note that this docker image has never been in a fully working state and I am not maintaining this repo.
If you read through all of the README, you should have noticed this but I will try to make this clearer in the future.

So If you still want to get this working, you'll probably need a lot of time and hair to pull out ^^

Regarding the issue:
seems to be caused by the "ovpn_run_tap"-script here:
 https://github.com/Hexxonite/docker-openvpn-tap/blob/dbf18137ec5ead01392e4fe9eaa53c0f03dc552f/bin/ovpn_run_tap#L64

You could simply try to remove the line, it should just cause the CA Key-Size to fallback to 2048 instead of 4096.
I Hope this helps, Cheers :)
